"""create users roles permissions tables

Revision ID: 874b07aa40c7
Revises: 
Create Date: 2026-06-29 18:02:48.238612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874b07aa40c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('resource', sa.String(length=100), nullable=False))
    op.add_column('permissions', sa.Column('action', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('code', sa.String(length=150), nullable=True))
    op.add_column('permissions', sa.Column('describtion', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('uuid', sa.UUID(), nullable=True))
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_unique_constraint('uq_permission_resource_action', 'permissions', ['resource', 'action'])
    op.execute(sa.text("UPDATE permissions SET uuid = gen_random_uuid() WHERE uuid IS NULL"))
    op.alter_column('permissions', 'uuid', existing_type=sa.UUID(), nullable=False)
    op.execute(sa.text("UPDATE permissions SET is_delete = COALESCE(is_delete, FALSE) WHERE is_delete IS NULL"))
    op.alter_column('permissions', 'is_delete', existing_type=sa.Boolean(), nullable=False)
    op.create_unique_constraint(None, 'permissions', ['uuid'])
    op.drop_column('permissions', 'name')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('describtion', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('uuid', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(sa.text("UPDATE roles SET describtion = COALESCE(describtion, 'No description') WHERE describtion IS NULL"))
    op.alter_column('roles', 'describtion',
               existing_type=sa.String(length=255),
               nullable=False)
    op.execute(sa.text("UPDATE roles SET uuid = gen_random_uuid() WHERE uuid IS NULL"))
    op.alter_column('roles', 'uuid', existing_type=sa.UUID(), nullable=False)
    op.execute(sa.text("UPDATE roles SET is_delete = COALESCE(is_delete, FALSE) WHERE is_delete IS NULL"))
    op.alter_column('roles', 'is_delete', existing_type=sa.Boolean(), nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_unique_constraint(None, 'roles', ['uuid'])
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('uuid', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.execute(sa.text("UPDATE users SET hashed_password = COALESCE(hashed_password, 'temporary-password') WHERE hashed_password IS NULL"))
    op.alter_column('users', 'hashed_password', existing_type=sa.String(length=255), nullable=False)
    op.execute(sa.text("UPDATE users SET is_active = COALESCE(is_active, TRUE) WHERE is_active IS NULL"))
    op.execute(sa.text("UPDATE users SET is_verified = COALESCE(is_verified, FALSE) WHERE is_verified IS NULL"))
    op.execute(sa.text("UPDATE users SET is_superuser = COALESCE(is_superuser, FALSE) WHERE is_superuser IS NULL"))
    op.alter_column('users', 'is_active', existing_type=sa.Boolean(), nullable=False)
    op.alter_column('users', 'is_verified', existing_type=sa.Boolean(), nullable=False)
    op.alter_column('users', 'is_superuser', existing_type=sa.Boolean(), nullable=False)
    op.execute(sa.text("UPDATE users SET uuid = gen_random_uuid() WHERE uuid IS NULL"))
    op.alter_column('users', 'uuid', existing_type=sa.UUID(), nullable=False)
    op.execute(sa.text("UPDATE users SET is_delete = COALESCE(is_delete, FALSE) WHERE is_delete IS NULL"))
    op.alter_column('users', 'is_delete', existing_type=sa.Boolean(), nullable=False)
    op.create_unique_constraint(None, 'users', ['uuid'])
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_delete')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'uuid')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_delete')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'uuid')
    op.drop_column('roles', 'describtion')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint('uq_permission_resource_action', 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('permissions', 'deleted_at')
    op.drop_column('permissions', 'is_delete')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    op.drop_column('permissions', 'uuid')
    op.drop_column('permissions', 'describtion')
    op.drop_column('permissions', 'code')
    op.drop_column('permissions', 'action')
    op.drop_column('permissions', 'resource')
    # ### end Alembic commands ###
